spring:
  application:
    name : oss-contribution-helper
  profiles:
    active: local

server:
  compression:
    enabled: true
    mime-types: application/json,application/json;charset=UTF-8,text/html,text/xml,text/plain
    min-response-size: 10240

github:
  token: ${GITHUB_TOKEN}
  issues-ttl-millis: 3600000
  summary-cdn-repo: ${SUMMARY_CDN_REPO:gshubhamCode/summary-cdn}

ollama:
  url: http://localhost
  port: 11434
  model: llama3.2

runpod:
  api-key: ${RUNPOD_API_KEY}
  vllm-api-Key: ${VLLM_API_KEY}
  vllm-pod-id: ${RUNPOD_VLLM_POD_ID}

cache:
  base-dir: ${CACHE_DIR:/workspace/volume/cache}

contribution:
  scheduler:
    enabled: true
    delay-ms: 7200000
    persist-file: config/scheduler-delay.json
