name: Build and Release Spring Boot Jar

on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build fat jar with Maven
        run: ./mvnw clean package -DskipTests

      # New step to list files so you can confirm jar name
      - name: List target directory
        run: ls -l target/

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Get version from pom.xml
        id: get_version
        run: |
          version=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.get_version.outputs.VERSION }}"
          name: "Release v${{ steps.get_version.outputs.VERSION }}"
          body: "Automated release for version ${{ steps.get_version.outputs.VERSION }}"
          draft: false
          prerelease: false

      # Dynamic jar detection and upload
      - name: Find jar file
        id: find_jar
        run: |
          jarfile=$(ls target/*.jar | head -n 1)
          echo "JARFILE=$jarfile" >> $GITHUB_OUTPUT

      - name: Upload Jar to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_jar.outputs.JARFILE }}
          asset_name: app.jar
          asset_content_type: application/java-archive
